# baseURL: "https://ambassadorlounge.com/"
baseURL: "https://ddwpu71jozkq2.cloudfront.net"
LanguageCode: "en-us"
Title: "The Ambassador Lounge"
Description: "The home of AWS APN Ambassador content"
theme: "hugo-nederburg-theme"
preserveTaxonomyNames: true
taxonomies:
  tag: tags
  category: categories
  ambassador: ambassadors
outputFormats:
  podcast:
    baseName: podcast
    isPlainText: true
    mediaType: application/rss+xml
outputs:
  home:
    - "html"
    - "rss"
    - "podcast"
paginate: 10