social:
  rss: true
Copyright:
  - All material linked to on this site is copyright per the original owners.
  - Site design based on Nederburg Hugo Theme by <a target="_blank" href="https://appernetic.io">Appernetic</a>
Description: Home of the Ambassador Lounge Podcast and other content by APN Ambassadors.